a=(1,4,5,6,7,8)
b=(5,6,7,8,9)
print("elements of list a are:",a)
print("elements of list b are:",b)
x=set(a)
y=set(b)
x.intersection_update(y)
print("common elements of list a and b are:",tuple(x))
z=set(a+b)
m=tuple(z)
print("concatenated result of list a and b is",m)
print("index number of element 9 is",m.index(9))
print(m*3)
